wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/wallpaper/.current
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wallpaper/.second
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/.config/hypr/wallpaper/.current
}

splash = false
