# https://wiki.hyprland.org/

### Sourcing external config files ###
$configs = $HOME/.config/hypr/configs # Default Configs directory path

#### General Settings ####
source= $configs/system_settings.conf # Default config for hypr 

#### Environment Vars ####
# see .conf/uwsm instead
# source= $configs/ENVariables.conf 

#### Keybinds ####
source=$configs/keybinds.conf

#### Autostart ####
source= $configs/startup_apps.conf 

#### Laptop Config ####
#source= $configs/laptops.conf 

#### Windows/Workspaces ####
source= $configs/window_rules.conf # Window Rules and Layer Rules (defaults)

#### Look and Feel ####
source= $configs/decorations.conf
source= $configs/animations.conf

#### Monitors ####
source= $configs/monitors.conf
