# Hyprland Wiki Links
# Animation - https://wiki.hyprland.org/Configuring/Animations/
# Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

source = $HOME/.config/hypr/macchiato.conf

$active = $mauve
$inactive = $lavender

general {
  border_size = 2
  gaps_in = 2
  gaps_out = 4

  col.active_border = $active
  col.inactive_border = $inactive
}

decoration {
  rounding = 10
  
  active_opacity = 1.0
  inactive_opacity = 0.9
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.1
  dim_special = 0.8

  shadow {
    enabled = true
    range = 3
    render_power = 1

    color =  $active
    color_inactive = $inactive
  }

  blur {
    enabled = true
    size = 6
    passes = 3
    new_optimizations = true
    xray = true
    ignore_opacity = true
    special = true
    popups = true
  }
}

group {
  col.border_active = $flamingo

	groupbar {
		col.active = $surface0
  }
}
